name = "key-vrilzhub"
main = "worker.js"
compatibility_date = "2024-01-01"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "vrilzhub_keys"
database_id = "bb7cd097-6692-4955-b3ec-e27e952cdf75"
